name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - SSO-signin
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Trigger Jenkins Build
        run: |
          curl -X POST "http://107.189.19.248:8080/job/your-jenkins-job/build" \
          --user "your-jenkins-user:your-jenkins-api-token"
